export const allMovies = [
  // Disney
  { title: 'Fantasia 2000', year: 2000, studio: 'Disney', page: 'disney' },
  { title: "The Emperor's New Groove", year: 2000, studio: 'Disney', page: 'disney' },
  { title: 'Atlantis: The Lost Empire', year: 2001, studio: 'Disney', page: 'disney' },
  { title: 'Lilo & Stitch', year: 2002, studio: 'Disney', page: 'disney' },
  { title: 'Treasure Planet', year: 2002, studio: 'Disney', page: 'disney' },
  { title: 'Brother Bear', year: 2003, studio: 'Disney', page: 'disney' },
  { title: 'Home on the Range', year: 2004, studio: 'Disney', page: 'disney' },
  { title: 'Chicken Little', year: 2005, studio: 'Disney', page: 'disney' },
  { title: 'Meet the Robinsons', year: 2007, studio: 'Disney', page: 'disney' },
  { title: 'Bolt', year: 2008, studio: 'Disney', page: 'disney' },
  { title: 'The Princess and the Frog', year: 2009, studio: 'Disney', page: 'disney' },
  { title: 'Tangled', year: 2010, studio: 'Disney', page: 'disney' },
  { title: 'Winnie the Pooh', year: 2011, studio: 'Disney', page: 'disney' },
  { title: 'Wreck-It Ralph', year: 2012, studio: 'Disney', page: 'disney' },
  { title: 'Frozen', year: 2013, studio: 'Disney', page: 'disney' },
  { title: 'Big Hero 6', year: 2014, studio: 'Disney', page: 'disney' },
  { title: 'Zootopia', year: 2016, studio: 'Disney', page: 'disney' },
  { title: 'Moana', year: 2016, studio: 'Disney', page: 'disney' },
  { title: 'Ralph Breaks the Internet', year: 2018, studio: 'Disney', page: 'disney' },
  { title: 'Frozen II', year: 2019, studio: 'Disney', page: 'disney' },
  { title: 'Raya and the Last Dragon', year: 2021, studio: 'Disney', page: 'disney' },
  { title: 'Encanto', year: 2021, studio: 'Disney', page: 'disney' },
  { title: 'Strange World', year: 2022, studio: 'Disney', page: 'disney' },
  { title: 'Wish', year: 2023, studio: 'Disney', page: 'disney' },
  { title: 'Moana 2', year: 2024, studio: 'Disney', page: 'disney' },
  { title: 'Zootopia 2', year: 2025, studio: 'Disney', page: 'disney' },

  // Pixar
  { title: 'Toy Story', year: 1995, studio: 'Pixar', page: 'pixar' },
  { title: "A Bug's Life", year: 1998, studio: 'Pixar', page: 'pixar' },
  { title: 'Toy Story 2', year: 1999, studio: 'Pixar', page: 'pixar' },
  { title: 'Monsters, Inc.', year: 2001, studio: 'Pixar', page: 'pixar' },
  { title: 'Finding Nemo', year: 2003, studio: 'Pixar', page: 'pixar' },
  { title: 'The Incredibles', year: 2004, studio: 'Pixar', page: 'pixar' },
  { title: 'Cars', year: 2006, studio: 'Pixar', page: 'pixar' },
  { title: 'Ratatouille', year: 2007, studio: 'Pixar', page: 'pixar' },
  { title: 'WALL·E', year: 2008, studio: 'Pixar', page: 'pixar' },
  { title: 'Up', year: 2009, studio: 'Pixar', page: 'pixar' },
  { title: 'Toy Story 3', year: 2010, studio: 'Pixar', page: 'pixar' },
  { title: 'Cars 2', year: 2011, studio: 'Pixar', page: 'pixar' },
  { title: 'Brave', year: 2012, studio: 'Pixar', page: 'pixar' },
  { title: 'Monsters University', year: 2013, studio: 'Pixar', page: 'pixar' },
  { title: 'Inside Out', year: 2015, studio: 'Pixar', page: 'pixar' },
  { title: 'The Good Dinosaur', year: 2015, studio: 'Pixar', page: 'pixar' },
  { title: 'Finding Dory', year: 2016, studio: 'Pixar', page: 'pixar' },
  { title: 'Cars 3', year: 2017, studio: 'Pixar', page: 'pixar' },
  { title: 'Coco', year: 2017, studio: 'Pixar', page: 'pixar' },
  { title: 'Incredibles 2', year: 2018, studio: 'Pixar', page: 'pixar' },
  { title: 'Toy Story 4', year: 2019, studio: 'Pixar', page: 'pixar' },
  { title: 'Onward', year: 2020, studio: 'Pixar', page: 'pixar' },
  { title: 'Soul', year: 2020, studio: 'Pixar', page: 'pixar' },
  { title: 'Luca', year: 2021, studio: 'Pixar', page: 'pixar' },
  { title: 'Turning Red', year: 2022, studio: 'Pixar', page: 'pixar' },
  { title: 'Lightyear', year: 2022, studio: 'Pixar', page: 'pixar' },
  { title: 'Elemental', year: 2023, studio: 'Pixar', page: 'pixar' },
  { title: 'Inside Out 2', year: 2024, studio: 'Pixar', page: 'pixar' },
  { title: 'Elio', year: 2025, studio: 'Pixar', page: 'pixar' },
  { title: 'Hoppers', year: 2026, studio: 'Pixar', page: 'pixar' },
  { title: 'Toy Story 5', year: 2026, studio: 'Pixar', page: 'pixar' },

  // DreamWorks
  { title: 'Antz', year: 1998, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'The Prince of Egypt', year: 1998, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'The Road to El Dorado', year: 2000, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Chicken Run', year: 2000, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Joseph: King of Dreams', year: 2000, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Shrek', year: 2001, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Spirit: Stallion of the Cimarron', year: 2002, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Sinbad: Legend of the Seven Seas', year: 2003, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Shrek 2', year: 2004, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Shark Tale', year: 2004, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Madagascar', year: 2005, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Wallace & Gromit: The Curse of the Were-Rabbit', year: 2005, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Over the Hedge', year: 2006, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Flushed Away', year: 2006, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Shrek the Third', year: 2007, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Bee Movie', year: 2007, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Kung Fu Panda', year: 2008, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Madagascar: Escape 2 Africa', year: 2008, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Monsters vs. Aliens', year: 2009, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'How to Train Your Dragon', year: 2010, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Shrek Forever After', year: 2010, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Megamind', year: 2010, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Kung Fu Panda 2', year: 2011, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Puss in Boots', year: 2011, studio: 'DreamWorks', page: 'dreamworks' },
  { title: "Madagascar 3: Europe's Most Wanted", year: 2012, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Rise of the Guardians', year: 2012, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'The Croods', year: 2013, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Turbo', year: 2013, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Mr. Peabody & Sherman', year: 2014, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'How to Train Your Dragon 2', year: 2014, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Penguins of Madagascar', year: 2014, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Home', year: 2015, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Kung Fu Panda 3', year: 2016, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Trolls', year: 2016, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'The Boss Baby', year: 2017, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Captain Underpants: The First Epic Movie', year: 2017, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'How to Train Your Dragon: The Hidden World', year: 2019, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Abominable', year: 2019, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Trolls World Tour', year: 2020, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'The Croods: A New Age', year: 2020, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Spirit Untamed', year: 2021, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'The Boss Baby: Family Business', year: 2021, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'The Bad Guys', year: 2022, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Puss in Boots: The Last Wish', year: 2022, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Ruby Gillman, Teenage Kraken', year: 2023, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Trolls Band Together', year: 2023, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Kung Fu Panda 4', year: 2024, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'The Wild Robot', year: 2024, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'Dog Man', year: 2025, studio: 'DreamWorks', page: 'dreamworks' },
  { title: 'The Bad Guys 2', year: 2025, studio: 'DreamWorks', page: 'dreamworks' },
  { title: "Gabby's Dollhouse: The Movie", year: 2025, studio: 'DreamWorks', page: 'dreamworks' },

  // Netflix
  { title: 'Klaus', year: 2019, studio: 'Netflix', page: 'netflix' },
  { title: 'I Lost My Body', year: 2019, studio: 'Netflix', page: 'netflix' },
  { title: 'The Willoughbys', year: 2020, studio: 'Netflix', page: 'netflix' },
  { title: 'Over the Moon', year: 2020, studio: 'Netflix', page: 'netflix' },
  { title: 'A Shaun the Sheep Movie: Farmageddon', year: 2020, studio: 'Netflix', page: 'netflix' },
  { title: 'Wish Dragon', year: 2021, studio: 'Netflix', page: 'netflix' },
  { title: 'Robin Robin', year: 2021, studio: 'Netflix', page: 'netflix' },
  { title: 'Back to the Outback', year: 2021, studio: 'Netflix', page: 'netflix' },
  { title: 'Vivo', year: 2021, studio: 'Netflix', page: 'netflix' },
  { title: 'The Sea Beast', year: 2022, studio: 'Netflix', page: 'netflix' },
  { title: "The Magician's Elephant", year: 2023, studio: 'Netflix', page: 'netflix' },
  { title: 'Nimona', year: 2023, studio: 'Netflix', page: 'netflix' },
  { title: 'Leo', year: 2023, studio: 'Netflix', page: 'netflix' },
  { title: 'Orion and the Dark', year: 2024, studio: 'Netflix', page: 'netflix' },
  { title: 'Thelma the Unicorn', year: 2024, studio: 'Netflix', page: 'netflix' },
  { title: 'Ultraman: Rising', year: 2024, studio: 'Netflix', page: 'netflix' },
  { title: 'Spellbound', year: 2024, studio: 'Netflix', page: 'netflix' },
  { title: 'Wallace & Gromit: Vengeance Most Fowl', year: 2025, studio: 'Netflix', page: 'netflix' },
  { title: 'In Your Dreams', year: 2025, studio: 'Netflix', page: 'netflix' },
  { title: 'Fixed', year: 2025, studio: 'Netflix', page: 'netflix' },
  { title: 'Pookoo', year: 2026, studio: 'Netflix', page: 'netflix' },

  // Illumination
  { title: 'Despicable Me', year: 2010, studio: 'Illumination', page: 'illumination' },
  { title: 'Hop', year: 2011, studio: 'Illumination', page: 'illumination' },
  { title: "Dr. Seuss' The Lorax", year: 2012, studio: 'Illumination', page: 'illumination' },
  { title: 'Despicable Me 2', year: 2013, studio: 'Illumination', page: 'illumination' },
  { title: 'Minions', year: 2015, studio: 'Illumination', page: 'illumination' },
  { title: 'The Secret Life of Pets', year: 2016, studio: 'Illumination', page: 'illumination' },
  { title: 'Sing', year: 2016, studio: 'Illumination', page: 'illumination' },
  { title: 'Despicable Me 3', year: 2017, studio: 'Illumination', page: 'illumination' },
  { title: "Dr. Seuss' The Grinch", year: 2018, studio: 'Illumination', page: 'illumination' },
  { title: 'The Secret Life of Pets 2', year: 2019, studio: 'Illumination', page: 'illumination' },
  { title: 'Sing 2', year: 2021, studio: 'Illumination', page: 'illumination' },
  { title: 'Minions: The Rise of Gru', year: 2022, studio: 'Illumination', page: 'illumination' },
  { title: 'The Super Mario Bros. Movie', year: 2023, studio: 'Illumination', page: 'illumination' },
  { title: 'Migration', year: 2023, studio: 'Illumination', page: 'illumination' },
  { title: 'Despicable Me 4', year: 2024, studio: 'Illumination', page: 'illumination' },
  { title: 'The Cat in the Hat', year: 2026, studio: 'Illumination', page: 'illumination' },
  { title: 'Minions 3', year: 2026, studio: 'Illumination', page: 'illumination' },

  // 20th Century
  { title: 'Titan A.E.', year: 2000, studio: '20th Century', page: 'twentieth' },
  { title: 'Ice Age', year: 2002, studio: '20th Century', page: 'twentieth' },
  { title: 'Robots', year: 2005, studio: '20th Century', page: 'twentieth' },
  { title: 'Ice Age: The Meltdown', year: 2006, studio: '20th Century', page: 'twentieth' },
  { title: "Garfield: A Tale of Two Kitties", year: 2006, studio: '20th Century', page: 'twentieth' },
  { title: "Everyone's Hero", year: 2006, studio: '20th Century', page: 'twentieth' },
  { title: 'The Simpsons Movie', year: 2007, studio: '20th Century', page: 'twentieth' },
  { title: "Dr. Seuss' Horton Hears a Who!", year: 2008, studio: '20th Century', page: 'twentieth' },
  { title: 'Ice Age: Dawn of the Dinosaurs', year: 2009, studio: '20th Century', page: 'twentieth' },
  { title: 'Fantastic Mr Fox', year: 2009, studio: '20th Century', page: 'twentieth' },
  { title: 'Rio', year: 2011, studio: '20th Century', page: 'twentieth' },
  { title: 'Ice Age: Continental Drift', year: 2012, studio: '20th Century', page: 'twentieth' },
  { title: 'Epic', year: 2013, studio: '20th Century', page: 'twentieth' },
  { title: 'The Book of Life', year: 2014, studio: '20th Century', page: 'twentieth' },
  { title: 'Rio 2', year: 2014, studio: '20th Century', page: 'twentieth' },
  { title: 'The Peanuts Movie', year: 2015, studio: '20th Century', page: 'twentieth' },
  { title: 'Ice Age: Collision Course', year: 2016, studio: '20th Century', page: 'twentieth' },
  { title: 'Ferdinand', year: 2017, studio: '20th Century', page: 'twentieth' },
  { title: 'Spies in Disguise', year: 2019, studio: '20th Century', page: 'twentieth' },
  { title: "Ron's Gone Wrong", year: 2021, studio: '20th Century', page: 'twentieth' },
  { title: "The Bob's Burgers Movie", year: 2022, studio: '20th Century', page: 'twentieth' },
  { title: 'The Day the Earth Blew Up: A Looney Tunes Movie', year: 2025, studio: '20th Century', page: 'twentieth' },
]

export const allSeries = [
  // Netflix Series
  { title: 'Arcane', year: 2021, category: 'Netflix Series', page: 'netflix-series', type: 'series', seasons:2 },
  { title: 'Blue Eye Samurai', year: 2023, category: 'Netflix Series', page: 'netflix-series', type: 'series', seasons:1 },
  { title: 'Castlevania', year: 2017, category: 'Netflix Series', page: 'netflix-series', type: 'series', seasons:4 },
  { title: 'Cyberpunk Edgerunners', year: 2022, category: 'Netflix Series', page: 'netflix-series', type: 'series', seasons:1 },
  { title: 'The Witcher: Nightmare of the Wolf', year: 2021, category: 'Netflix Series', page: 'netflix-series', type: 'series', seasons:1 },
  { title: 'Kipo and the Age of Wonderbeasts', year: 2020, category: 'Netflix Series', page: 'netflix-series', type: 'series', seasons:3 },

  // Korean Series
  { title: 'Solo Leveling', year: 2024, category: 'Korean Series', page: 'korean-series', type: 'series', seasons:1 },
  { title: 'The God of High School', year: 2020, category: 'Korean Series', page: 'korean-series', type: 'series', seasons:1 },
  { title: 'Tower of God', year: 2020, category: 'Korean Series', page: 'korean-series', type: 'series', seasons:1 },
  { title: 'Noblesse', year: 2020, category: 'Korean Series', page: 'korean-series', type: 'series', seasons:1 },
  { title: 'Lookism', year: 2022, category: 'Korean Series', page: 'korean-series', type: 'series', seasons:1 },
  { title: 'Hellbound', year: 2021, category: 'Korean Series', page: 'korean-series', type: 'series', seasons:2 },

  // Japanese Series
  { title: 'Attack on Titan', year: 2013, category: 'Japanese Series', page: 'japanese-series', type: 'series', seasons:4 },
  { title: 'Demon Slayer', year: 2019, category: 'Japanese Series', page: 'japanese-series', type: 'series', seasons:4 },
  { title: 'Jujutsu Kaisen', year: 2020, category: 'Japanese Series', page: 'japanese-series', type: 'series', seasons:2 },
  { title: 'One Piece', year: 1999, category: 'Japanese Series', page: 'japanese-series', type: 'series', seasons: 20 },
  { title: 'Naruto', year: 2002, category: 'Japanese Series', page: 'japanese-series', type: 'series', seasons:5 },
  { title: 'Bleach', year: 2004, category: 'Japanese Series', page: 'japanese-series', type: 'series', seasons:4 },
  { title: 'My Hero Academia', year: 2016, category: 'Japanese Series', page: 'japanese-series', type: 'series', seasons:7 },
  { title: 'Fullmetal Alchemist Brotherhood', year: 2009, category: 'Japanese Series', page: 'japanese-series', type: 'series', seasons:1 },
  { title: 'Death Note', year: 2006, category: 'Japanese Series', page: 'japanese-series', type: 'series', seasons:1 },
  { title: 'Dragon Ball Z', year: 1989, category: 'Japanese Series', page: 'japanese-series', type: 'series', seasons:9 },
]